"""
FEM-backed directional-coupler model.

Loads the supermode data generated by ``fdtd/coupler_modes.py`` (femwell FEM
eigenmode analysis) and exposes the coupler's cross-port power as a function
of wavelength and gap -- computed from first-principles n_even/n_odd, not from
hand-chosen coefficients.

The 50:50 design point is a fixed physical coupler length L_3dB chosen at the
nominal gap/wavelength; its splitting then varies with wavelength and gap
exactly as the FEM-solved coupling length L_pi(lambda, gap) dictates:

    P_cross(lambda, gap) = sin^2( pi * L_3dB / (2 * L_pi(lambda, gap)) ).

If the data file is absent, callers should fall back to the analytic
``components.dc_cross_coupling`` (clearly labeled as a placeholder).
"""

from __future__ import annotations
import json
import os
import numpy as np

_DATA_PATH = os.path.join(os.path.dirname(__file__), "..",
                          "results", "coupler_fem_backed.json")


class FEMCouplerModel:
    def __init__(self, data_path: str = _DATA_PATH):
        with open(data_path) as f:
            self.d = json.load(f)
        self.lam0 = self.d["nominal"]["wavelength_um"]
        self.gap0 = self.d["nominal"]["gap_um"]
        self.L_3dB = self.d["nominal"]["L_3dB_um"]

        gs = self.d["gap_sweep"]
        self._gap = np.array(gs["gap_um"])
        self._Lpi_gap = np.array(gs["L_pi_um"])
        ws = self.d["wavelength_sweep"]
        self._lam = np.array(ws["wavelength_um"])
        self._Lpi_lam = np.array(ws["L_pi_um"])

        # Separable model: L_pi(lam, gap) = L_pi_lam(lam) * [L_pi_gap(gap)/L_pi_gap(gap0)]
        self._Lpi_gap0 = float(np.interp(self.gap0, self._gap, self._Lpi_gap))

    def L_pi(self, wavelength_um: float, gap_um: float | None = None) -> float:
        gap_um = self.gap0 if gap_um is None else gap_um
        Lpi_lam = float(np.interp(wavelength_um, self._lam, self._Lpi_lam))
        gap_factor = float(np.interp(gap_um, self._gap, self._Lpi_gap)) \
            / self._Lpi_gap0
        return Lpi_lam * gap_factor

    def cross_power(self, wavelength_um: float,
                    gap_um: float | None = None,
                    length_um: float | None = None) -> float:
        L = self.L_3dB if length_um is None else length_um
        Lpi = self.L_pi(wavelength_um, gap_um)
        return float(np.sin(np.pi * L / (2.0 * Lpi)) ** 2)


# module-level singleton (lazy)
_MODEL: FEMCouplerModel | None = None


def get_model() -> FEMCouplerModel | None:
    global _MODEL
    if _MODEL is None:
        try:
            _MODEL = FEMCouplerModel()
        except FileNotFoundError:
            return None
    return _MODEL


def dc_cross_coupling_fem(wavelength_um: float,
                          gap_um: float = 0.20) -> float:
    """FEM-backed cross-port power; raises if the data file is missing."""
    m = get_model()
    if m is None:
        raise FileNotFoundError(
            "coupler_fem_backed.json not found; run fdtd/coupler_modes.py")
    return m.cross_power(wavelength_um, gap_um)
